[package]
name = "lilufo"
version = "0.1.0"
edition = "2021"

[dependencies]
norad = "0.14.2"
clap = { version = "4.3", features = ["derive"] }
anyhow = "1.0"
xmltree = "0.11"
glob = "0.3"
plist = "1.5"
